### ISSUE TITLE
Добавляем сборку отчета

### ISSUE THREAD

**Issue by eroshenkoam** [eroshenkoam/swagger-coverage-example#8]
Файлик `.github/workflows/build.yml`

```
name: Build

on:
  pull_request:
    branches:
      - '*'
  push:
    branches:
      - 'master'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Test
        run: ./gradlew clean test
      - name: Coverage
        run: ./gradlew coverageReport
      - uses: actions/upload-artifact@v2
        with:
          name: coverage.html
          path: coverage.html
```
